@startuml parisportif5
class User
class Wallet
class Currency
class Cart
class Bet
class Odds
class Amount
class Payment
class Billing
class History
class Location
class Sport
class Country
class Competition
class Event
class Race
class Fixture
class Date
class Time
class Period
class Teams
class Score
class Result
class Status
class PlayerStatus
class Player
class Team
@enduml