@startuml parisportif5

'plantuml
'Relations :
    User --|> Account
    BetCategory "1" <-- "0..*" Bet
    User "1" -- "1" BettingHistory
    User "1" -- "1" Wallet
    User "1" -- "1" Cart
    Bet "0..*" -- "0..*" Cart
    BettingHistory "0..1" -- "0..*" Bet
    BetCategory "0..*" --> "1" Sport
    Competition "1" o-- "0..*" Event
    Event "1" o-- "0..*" Run
    Run "1" -- "1" Location
    Team "1" o-- "0..*" Score
    Run "1" *--> "1..*" Team
    Team "1" *-- "1..*" Member
    Sport "0..1" --> "1" Country
    Location "0..*" --> "1" Country
    Wallet "1" -- "0..*" Billing
    BetTargetInterface <|.. Competition
    BetTargetInterface <|.. Event
    BetTargetInterface <|.. Run
    BetTargetInterface <|.. Team
    BetTargetInterface <|.. Member
'Définitions des classes :
    'Porte-feuille de l'utilisateur avec des fonds (de l'argent gagnés)
    class Wallet {
        -identifier : int
        -user : User
        -amount : float
        -billings : Billing[*]
    }
    'Panier qui contient les paris sélectionnés
    class Cart {
        -identifier : int
        -user : User
        -betsList : Bet[*]
    }
    'Historique des paris gagnés ou perdus
    class BettingHistory {
        -identifier : int
        -user : User
        -betsList : Bet[*]
    }
    'interface de généralisation pour les classes autorisé à être parié
    interface BetTargetInterface {
        +getOdds() : float
    }
    'Compte (sert à ce connecter)
    class Account {
        #identifier : int
        #validation : bool
        #password : string
        #emailAddress : string
        #status : bool
        +isValidate() : bool
    }
    'Utilisateur avec un compte
    class User {
        -identifier : int
        -name : string
        -lastName : string
        -billingAddress : string
        -billingPostCode : string
        -billingCountry : string
        -birthDate : DateTime
        -wallet : Wallet
        -cart : Cart
        -bettingHistory : BettingHistory
    }
    note left : Possible propriété mobile pour notification
    'Factures (type=débit ou crédit)
    class Billing {
        -identifier : int
        -orderNumber  : int
        -amount : float
        -currency : string
        -user : User
        -type : int
    }
    'Historique des factures (type=débit ou crédit)
    class BillingHistory {
        -identifier : int
        -name : string
        -lastName : string
        -billingAddress : string
        -billingPostCode : string
        -billingCountry : string
        -orderNumber  : int
        -amount : float
        -currency : string
        -type : int
    }
    'Un paris
    class Bet {
        -identifier : int
        -amount : float
        -state : BetState
        -user : User
        -category : BetCategory
        -odds : float
        -items : BetTargetInterface
    }
    'Catégorie de paris (ex: Paris sur la victoire du favoris)
    class BetCategory {
        -identifier : int
        -name : string
        -description : string
        -sport : Sport
    }
    'Lieu de la rencontre/course
    class Location {
        -identifier : int
        -place : string
        -timezoneLocal : DateTimeZone
        -country : Country
        -run : Run
    }
    'Sport pratiqué (runtype = fixture, race) (type = collectif ou individuel ou les deux)
    class Sport {
        -identifier : int
        -name : string
        -numberOfCompetitor : int
        -type : SportType[*]
        -runType : string
        -country : Country
    }
    'Pays du lieu de la rencontre/course
    class Country {
        -identifier : int
        -name : string
        -TimeZones : DateTimeZone[*]
        +getDefaultTimeZone() : DateTimeZone
        +getTimeZone(in string timezone) : DateTimeZone
    }
    'Compétition (JO, Ligue des Champions, F1 Championnat du monde)
    class Competition {
        -identifier : int
        -name : string
        -startDate : DateTime
        -endDate : DateTime
        -odds : float
        -events : Event[*]
        -winner : Team
        +getOdds() : float
    }
    'Événement de la compétition (poul de qualification, Circuit F1 de france)
    class Event {
        -identifier : int
        -name : string
        -startDate : DateTime
        -endDate : DateTime
        -odds : float
        -competition : Competition
        -runs : Run[*]
        +getOdds() : float
    }
    'Classe mère global : Un match, une rencontre, une course
    class Run {
        -identifier : int
        -name : string
        -startDate : DateTime
        -endDate : DateTime
        -odds : float
        -location : Location
        -event : Event
        -teams : Team[*]
        -result : Team|null
        +getOdds() : float
    }
    note top of Run
    Extension possible en plus de Team : "Competitor".
    Futur amélioration possible de Result en un classement.
    end note
    'Score de l'équipe ou du membre de l'équipe
    class Score {
        -identifier : int
        -value : int
        -type : string
        -team : Team
        +getScore() : int
    }
    'Joueur ou sportif ou pilote
    class Member {
        -identifier : int
        -name : string
        -firstName : string
        -status : MemberStatus
        -result : ResultType
        -role : MemberRole
        -odds : float
        -team : Team
        +getOdds() : float
    }
    'Équipes qui participe à une rencontre, à une course
    class Team {
        -identifier : int
        -name : string
        -odds : float
        -result : ResultType
        -scores : Score[*]
        -members : Member[*]
        +getOdds() : float
    }
    note right: Peut implémenter une interface ContestantInterface

@enduml