@startuml parisportif5
skinparam linetype ortho
'plantuml
'Relations :
    'Un utilisateur a une langue sélectionnée
    User "0..*" --> "1" Language
    'Une facture n'est pas pas forcément lié à un utilisateur existant
    User "0..1" <-- "0..*" Billing
    'Un paris a un type
    BetCategory "1" <-- "0..*" Bet
    'Un utilisateur a un porte-feuille
    User "1" -- "1" Wallet
    'Un utilisateur a des paris
    User "1" o-- "0..*" Bet
    'La compétition a une équipe gagnante
    Competition "0..*" --> "0..1" Team
    'Une compétition a plusieurs rencontre ou course
    Competition "1" o-- "0..*" Run
    'Une rencontre ou une course a un lieu
    Run "0..*" --> "1" Location
    'Une rencontre ou une course a plusieurs équipes
    Run "1" o--> "0..*" Team
    'Une équipe a plusieurs membre
    Team "1" *-- "1..*" Member
    'Une compétition a un sport
    Sport "1" <-- "0..*" Competition
    'Une compétition a une liste de catégorie de paris
    BetCategory "1..*" <-- "0..*" Competition
    'Une équipe a un sport
    Sport "1" <-- "0..*" Team
    'Un membre a un rôle (fonction) tel que pilote, joueur
    MemberRole "1" <-- "0..*" Member
    'Un membre a un status (blessé, titulaire)
    MemberStatus "1" <-- "0..*" Member
    'Liaison potentiel entre un paris et une compétition
    Bet "0..*" --> "1" Competition
    'Liaison potentiel entre un paris et une rencontre ou course
    Bet "0..*" --> "0..1" Run
    'Liaison potentiel entre un paris et une équipe
    Bet "0..*" --> "0..1" Team
    'Liaison potentiel entre un paris et un membre
    Bet "0..*" --> "0..1" Member
    'Implémentation de l'interface FundsStorageInterface par l'objet FundsStorageDataConverter
    FundsStorageInterface <|.. FundsStorageDataConverter
    'Implémentation de l'interface CommissionRateStorageInterface par l'objet CommissionRateStorageDataConverter
    CommissionRateStorageInterface <|.. CommissionRateStorageDataConverter
    'Implémentation de l'interface OddsStorageInterface par l'objet OddsStorageDataConverter
    OddsStorageInterface <|.. OddsStorageDataConverter
    'Implémentation de l'interface DateTimeStorageInterface par l'objet DateTimeStorageDataConverter
    DateTimeStorageInterface <|.. DateTimeStorageDataConverter
    'Implémentation de l'interface FundsStorageInterface par l'objet StorageDataConverter
    FundsStorageInterface <|.. StorageDataConverter
    'Implémentation de l'interface CommissionRateStorageInterface par l'objet StorageDataConverter
    CommissionRateStorageInterface <|.. StorageDataConverter
    'Implémentation de l'interface OddsStorageInterface par l'objet StorageDataConverter
    OddsStorageInterface <|.. StorageDataConverter
    'Implémentation de l'interface DateTimeStorageInterface par l'objet StorageDataConverter
    DateTimeStorageInterface <|.. StorageDataConverter
    '
    DateTimeStorageDataConverter "1" <-- "0..*" Bet
    '
    DateTimeStorageDataConverter "1" <-- "0..*" Competition
    '
    DateTimeStorageDataConverter "1" <-- "0..*" Run
    '
    DateTimeStorageDataConverter "1" <-- "0..*" Billing
    '
    DateTimeStorageDataConverter "1" <-- "0..*" User
'Définitions des classes :
    'DateTimeStorageDataConverter
    'Pour convertir le montant enregistré dans la BDD en unité monétaire et vice versa
    interface FundsStorageInterface {
        +convertToCurrencyUnit(in int amount) : float
        +convertCurrencyUnitToStoredData(in float amount) : int
    }
    'Pour convertir le taux de commission enregistré dans la BDD en pourcentage et vice versa
    interface CommissionRateStorageInterface {
        +convertToCommissionRate(in int commissionRate) : float
        +convertCommissionRateToStoredData(in float commissionRate) : int
    }
    'Pour convertir la côte enregistré dans la BDD en float et vice versa
    interface OddsStorageInterface {
        +convertToOddsMultiplier(in int odds) : float
        +convertOddsMultiplierToStoredData(in float odds) : int
    }
    'Pour convertir la date et heure au format de la BDD
    interface DateTimeStorageInterface {
        +convertedToStoreDateTime(in DateTimeInterface datetime) : DateTimeImmutable
        +setStoredTimezone(inout DateTimeImmutable datetimeImmutable) : DateTimeImmutable
    }
    class DateTimeStorageDataConverter {
        +{static} STORED_TIME_ZONE : string = 'UTC'
    }
    class StorageDataConverter {
        +{static} getStoredTimeZone() : string
    }
    'Rôle du membre (pilote, co-pilote, joueur)
    class MemberRole {
        -identifier : int
        -name : string
    }
    'Statut du membre (blessé, remplaçant, titulaire)
    class MemberStatus {
        -identifier : int
        -name : string
    }
    'Porte-feuille de l'utilisateur avec des fonds (de l'argent gagnés)
    class Wallet {
        -identifier : int
        -amount : int
        +add(in float value) : void
        +subtract(in float value) : void
        +isEmpty() : bool
        +isAuthorizedSubtraction(in float value) : bool
    }
    'Utilisateur avec un compte
    class User {
        -id : int
        -email : string
        -password : string
        -plainPassword : string|null
        -roles : string[]
        -activatedStatus : bool
        -activatedDate : DateTimeImmutable
        -suspendedStatus : bool
        -suspendedDate : DateTimeImmutable
        -deletedStatus : bool
        -deletedDate : DateTimeImmutable
        -civility : string
        -firstName : string
        -lastName : string
        -billingAddress : string
        -billingCity : string
        -billingPostcode : string
        -billingCountry : string
        -birthDate : DateTimeImmutable
        -timeZoneSelected : string
        +{static} MIN_AGE_FOR_BETTING : int = 18
        +{static} MAX_AGE_FOR_BETTING : int = 140
        +{static} SELECT_CURRENCY_CODE : string = "EUR"
        +{static} SELECT_CURRENCY_SYMBOL : string = "€"
        +getName() : string
        +getAddress() : string
        +isPasswordSafe() : bool
        +getSalt() : string|null
        +eraseCredentials() : void
        +delete() : bool
        +restore() : bool
        +suspend() : bool
        +valid() : bool
        +activate() : bool
        +desactivate() : bool
        +cancelBet(in Bet bet) : void
        +isAdmin() : bool
    }
    'Langue d'affichage de l'utilisateur
    class Language {
        -identifier : int
        -name : string
        -country : string
        -code : string
        -dateFormat : string
        -timeFormat : string
        -timeZone : string
        +isValidDateTimeFormat() : bool
        +getDateTimeFormat() : string|null
    }
    'Factures (type=débit ou crédit)
    class Billing {
        -identifier : int
        -firstName : string
        -lastName : string
        -address : string
        -city : string
        -postcode : string
        -country : string
        -designation : string
        -orderNumber : int
        -invoiceNumber : int
        -amount : int
        -commissionRate : int
        -operationType : string
        -issueDate : DateTimeImmutable
        -deliveryDate : DateTimeImmutable
        +{static} DEFAULT_COMMISSION_RATE : float =  7.5
        +{static} DEFAULT_CURRENCY_CODE : string = "EUR"
        +{static} DEFAULT_CURRENCY_SYMBOL : string = "€"
        +{static} DEBIT : string = "debit"
        +{static} CREDIT : string = "credit"
        +{static} OPERATION_TYPES : string[] = [DEBIT, CREDIT]
        +getName() : string
        +getAddress() : string
        +deleteUser() : void
        +hasUser() : bool
    }
    'Un paris
    class Bet {
        -identifier : int
        -designation : string
        -amount : int
        -odds : int
        -betDate : DateTimeImmutable
        -isWinning : bool|null
        +hasWon() : bool|null
        +won() : void
        +lost() : void
        +restoreWithoutResult() : void
        +getTarget() : Member|Team
        +getSelected() : Run|Competition
    }
    'Catégorie de paris (ex: Paris sur le résultat)
    class BetCategory {
        -identifier : int
        -name : string
        -allowDraw : bool
        -target : string
        -description : string
        +{static} TEAM_TYPE : string = "teams"
        +{static} MEMBER_TYPE : string = "members"
        +{static} TARGET_TYPES : string[] = [TEAM_TYPE, MEMBER_TYPE]
    }
    'Lieu de la rencontre/course
    class Location {
        -identifier : int
        -place : string
        -timezone : string
        -country : string
    }
    'Sport pratiqué (runtype = fixture(match), race(course)) (type = collectif ou individuel ou les deux)
    class Sport {
        -identifier : int
        -name : string
        -maxTeamsByRun : int|null
        -maxMembersByTeam : int|null
        -minTeamsByRun : int
        -minMembersByTeam : int
        -collectiveType : bool
        -individualType : bool
        -country : string
        -runType : string
        +{static} FIXTURE_TYPE : string = "fixture"
        +{static} RACE_TYPE : string = "race"
        +{static} RUN_TYPES : string[] = [FIXTURE_TYPE, RACE_TYPE]
        +isCollective() : bool
        +isIndividual() : bool
        +isBothIndividualAndCollective() : bool
    }
    'Compétition (JO, Ligue des Champions, F1 Championnat du monde)
    class Competition {
        -identifier : int
        -name : string
        -startDate : DateTimeImmutable
        -endDate : DateTimeImmutable
        -country : string
        -maxRuns : int|null
        -minRuns : int
        +hasRuns() : bool
        +isFinish() : bool
        +isOngoing() : bool
        +getEventsCount() : int
        +getRunsCount() : int
        +hasRequiredNumberOfRuns() : bool
    }
    'Un match, une rencontre, une course
    class Run {
        -identifier : int
        -event : string
        -name : string
        -startDate : DateTimeImmutable
        -endDate : DateTimeImmutable
        +isFinish() : bool
        +isOngoing() : bool
        +hasTeams() : bool
        +getTeamsCount() : int
        +hasRequiredNumberOfTeams() : bool
    }
    'Joueur ou sportif ou pilote
    class Member {
        -identifier : int
        -lastName : string
        -firstName : string
        -country : string
        -odds : int
    }
    'Équipes qui participe à une rencontre, à une course
    class Team {
        -identifier : int
        -name : string
        -country : string
        -odds : int
        +hasMembers() : bool
        +getMembersCount() : int
        +getScoresCount() : int
        +hasRequiredNumberOfMembers() : bool
    }
@enduml
