# This is a basic workflow
name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  tests:
    name: Tests

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Install composer
        uses: php-actions/composer@v1
        with:
          php_version: 7.4
          composer_version: 1

      # Tests de conformité du code
      - uses: hrysd/action-php_codesniffer@v1
        with:
          standard: PSR12
          target_directory: src

      - run: ./vendor/bin/phpcs src --extensions=php --report=code --colors --report-width=80 --standard=PSR12 --ignore=src/Kernel.php
        
  syntax-tests:
    name: Tests de syntaxe

    needs: composer-caching

    runs-on: ubuntu-latest

    steps:

      - name: Checkout project
        uses: actions/checkout@v2

      - name: Install composer
        uses: php-actions/composer@v1
        with:
          php_version: 7.4
          composer_version: 1

      - name: Installs phpstan latest version
        uses: php-actions/phpstan@v1
          
      - name: Runs phpstan tests
        run: ./vendor/bin/phpstan --no-interaction --no-progress analyse -c phpstan.neon.dist

      # Tests unitaires
      - name: Installs phpunit latest version
        uses: php-actions/phpunit@17-php-versions
        with:
          bootstrap: vendor/autoload.php
          configuration: tests/phpunit.xml.dist

      - name: Runs phpunit tests
        run: php bin/phpunit --configuration 'tests/phpunit.xml.dist' --bootstrap 'vendor/autoload.php' --test-suffix 'Test.php,.phpt' tests
